name: Sims
# Sims workflow runs multiple types of simulations (nondeterminism, import-export, after-import, multi-seed-short)
# This workflow will run on all Pull Requests, if a .go, .mod or .sum file have been changed
on:
  pull_request:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
  push:
    branches:
      - main

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.3.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  check-diff:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-sims')"
    outputs:
      should-run: ${{ env.GIT_DIFF }}
    steps:
    - uses: actions/checkout@v3
    - uses: technote-space/get-diff-action@v6.0.1
      with:
        PATTERNS: |
          **/**.go
          go.mod
          go.sum
        SET_ENV_NAME_INSERTIONS: 1
        SET_ENV_NAME_LINES: 1

  setup:
    runs-on: ubuntu-latest
    needs: check-diff
    if: needs.check-diff.outputs.should-run
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2.1.7
        id: cache-setup
        with:
          path: |
            ~/go/bin
          key: ${{ runner.os }}-sims-t1
      - uses: technote-space/get-diff-action@v6.0.1
        if: steps.cache-setup.outputs.cache-hit != 'true'
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
          SET_ENV_NAME_INSERTIONS: 1
          SET_ENV_NAME_LINES: 1
      - name: Install cleveldb
        if: env.GIT_DIFF
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y libleveldb-dev
          sudo apt-get install -y libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev
      - name: Build rocksdb
        if: env.GIT_DIFF
        run: |
          export ROCKSDB_SUDO='true'
          make rocksdb
      - uses: actions/setup-go@v3
        if: env.GIT_DIFF
        with:
          go-version: 1.17
      - name: Display go version
        if: env.GIT_DIFF
        run: go version
      - name: Install provenanced
        if: env.GIT_DIFF
        run: make install
      - name: Install runsim
        if: env.GIT_DIFF
        run: export GO111MODULE="on" && go get github.com/cosmos/tools/cmd/runsim@v1.0.0

  simple-goleveldb:
    runs-on: ubuntu-latest
    needs: [setup, check-diff]
    if: needs.check-diff.outputs.should-run
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2.1.7
        id: cache-setup
        with:
          path: |
            /usr/local/rocksdb
            /usr/local/cleveldb
            ~/go/bin
          key: ${{ runner.os }}-sims-t1
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Display versions
        run: |
          go version
          provenanced version --long
      - name: test-sim-simple goleveldb
        run: make test-sim-simple

  simple-cleveldb:
    runs-on: ubuntu-latest
    needs: [setup, check-diff]
    if: needs.check-diff.outputs.should-run
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2.1.7
        id: cache-setup
        with:
          path: |
            /usr/local/rocksdb
            /usr/local/cleveldb
            ~/go/bin
          key: ${{ runner.os }}-sims-t1
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Display versions
        run: |
          go version
          provenanced version --long
      - name: test-sim-simple cleveldb
        run: make DB_BACKEND=cleveldb test-sim-simple

  simple-rocksdb:
    runs-on: ubuntu-latest
    needs: [setup, check-diff]
    if: needs.check-diff.outputs.should-run
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2.1.7
        id: cache-setup
        with:
          path: |
            /usr/local/rocksdb
            /usr/local/cleveldb
            ~/go/bin
          key: ${{ runner.os }}-sims-t1
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Display versions
        run: |
          go version
          provenanced version --long
      - name: test-sim-simple rocksdb
        run: make DB_BACKEND=rocksdb test-sim-simple

  simple-badgerdb:
    runs-on: ubuntu-latest
    needs: [setup, check-diff]
    if: needs.check-diff.outputs.should-run
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2.1.7
        id: cache-setup
        with:
          path: |
            /usr/local/rocksdb
            /usr/local/cleveldb
            ~/go/bin
          key: ${{ runner.os }}-sims-t1
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Display versions
        run: |
          go version
          provenanced version --long
      - name: test-sim-simple badgerdb
        run: make DB_BACKEND=badgerdb test-sim-simple

  nondeterminism:
    runs-on: ubuntu-latest
    needs: [setup, check-diff]
    if: needs.check-diff.outputs.should-run
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2.1.7
        id: cache-setup
        with:
          path: |
            /usr/local/rocksdb
            /usr/local/cleveldb
            ~/go/bin
          key: ${{ runner.os }}-sims-t1
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Display versions
        run: |
          go version
          provenanced version --long
      - name: test-sim-nondeterminism
        run: make test-sim-nondeterminism

  import-export-goleveldb:
    runs-on: ubuntu-latest
    needs: [setup, check-diff]
    if: needs.check-diff.outputs.should-run
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2.1.7
        id: cache-setup
        with:
          path: |
            /usr/local/rocksdb
            /usr/local/cleveldb
            ~/go/bin
          key: ${{ runner.os }}-sims-t1
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Display versions
        run: |
          go version
          provenanced version --long
      - name: test-sim-import-export goleveldb
        run: make test-sim-import-export

  import-export-cleveldb:
    runs-on: ubuntu-latest
    needs: [setup, check-diff]
    if: needs.check-diff.outputs.should-run
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2.1.7
        id: cache-setup
        with:
          path: |
            /usr/local/rocksdb
            /usr/local/cleveldb
            ~/go/bin
          key: ${{ runner.os }}-sims-t1
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Display versions
        run: |
          go version
          provenanced version --long
      - name: test-sim-import-export cleveldb
        run: make DB_BACKEND=cleveldb test-sim-import-export

  import-export-rocksdb:
    runs-on: ubuntu-latest
    needs: [setup, check-diff]
    if: needs.check-diff.outputs.should-run
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2.1.7
        id: cache-setup
        with:
          path: |
            /usr/local/rocksdb
            /usr/local/cleveldb
            ~/go/bin
          key: ${{ runner.os }}-sims-t1
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Display versions
        run: |
          go version
          provenanced version --long
      - name: test-sim-import-export rocksdb
        run: make DB_BACKEND=rocksdb test-sim-import-export

  import-export-badgerdb:
    runs-on: ubuntu-latest
    needs: [setup, check-diff]
    if: needs.check-diff.outputs.should-run
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2.1.7
        id: cache-setup
        with:
          path: |
            /usr/local/rocksdb
            /usr/local/cleveldb
            ~/go/bin
          key: ${{ runner.os }}-sims-t1
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Display versions
        run: |
          go version
          provenanced version --long
      - name: test-sim-import-export badgerdb
        run: make DB_BACKEND=badgerdb test-sim-import-export

  multi-seed-short:
    runs-on: ubuntu-latest
    needs: [setup, check-diff]
    if: needs.check-diff.outputs.should-run
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2.1.7
        id: cache-setup
        with:
          path: |
            /usr/local/rocksdb
            /usr/local/cleveldb
            ~/go/bin
          key: ${{ runner.os }}-sims-t1
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Display versions
        run: |
          go version
          provenanced version --long
      - name: test-sim-multi-seed-short
        run: make test-sim-multi-seed-short
